// generated by scripts/build-site.js — do not edit
const CACHE = 'vbb-bob-0.4.4-dfe6ce58';
const PRECACHE = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./icon-192.png",
  "./icon-512.png",
  "../shared/vbb-crypto.js",
  "../shared/vbb-codec.js",
  "../shared/vbb-qr.js",
  "../shared/vbb.wasm",
  "../shared/vbb_final.zkey",
  "../shared/vendor/circomlibjs.esm.js",
  "../shared/vendor/buffer.esm.js",
  "../shared/vendor/snarkjs.min.js",
  "../shared/vendor/jsQR.js",
  "../shared/vendor/qrcode.min.js"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('vbb-bob-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(resp => {
      if (resp.ok && new URL(e.request.url).origin === location.origin) {
        const copy = resp.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
      }
      return resp;
    }))
  );
});
